export const SEND_SHIPPING_INFORMATION = 'SEND_SHIPPING_INFORMATION';
export const ADD_COUPON = 'ADD_COUPON';
export const GET_COUPON = 'GET_COUPON';
export const DELETE_COUPON = 'DELETE_COUPON';

export const SET_COUPON_UPDATING = 'SET_COUPON_UPDATING';
