export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCT_FILTERS = 'PRODUCT_FILTERS';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const ADD_TO_BASKET_IN_PROGRESS = 'ADD_TO_BASKET_IN_PROGRESS';
