name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  create:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: List contents of GITHUB_WORKSPACE
      run: |
        echo "${{ secrets.SSH }}"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Set up environment variables
      run:
        echo "${{ secrets.ENV_STAGE }}" > .env.stage1

    - name: Run rnuc .env.stage1
      run: npx rnuc .env.stage1

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install --project-directory=ios

    # - name: Build iOS app
    #   run: |
    #     cd ios
    #     xcodebuild -workspace Ryman.xcworkspace -scheme ryman -destination 'platform=iOS Simulator,name=iPhone 11' build VERBOSE=1

    # - name: Archive artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: ios-build
    #     path: ios/build/Build/Products/Debug-iphonesimulator/Ryman.app
    # - name: Create IPA
    #   run:  xcodebuild -exportArchive -archivePath ios/Ryman.xcarchive -exportPath Ryman -exportOptionsPlist ExportOptions.plist

    - name: build archive
      run: |
        cd ios
        xcodebuild -workspace ryman.xcworkspace \
        -scheme "ryman" \
        -sdk iphoneos \
        -configuration  \
        -destination generic/platform=iOS \
        -archivePath $RUNNER_TEMP/ryman.xcarchive \
        archive 

    - name: export ipa
        env:
          EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
        run: |
          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
          echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
          xcodebuild -exportArchive \
          -archivePath $RUNNER_TEMP/joplin.xcarchive \
          -exportOptionsPlist $EXPORT_OPTS_PATH \
          -exportPath $RUNNER_TEMP/build   

    - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{ runner.temp }}/build/Joplin.ipa
          # you can also archive the entire directory 
          # path: ${{ runner.temp }}/build
          retention-days: 3