name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  create:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
      - name: checkout repository
        uses: actions/checkout@v3
      - name: List contents of GITHUB_WORKSPACE
        run: |
          echo "${{ secrets.SSH }}"

      - name: Debug Workflow Variables
        run: |
          echo "CERTIFICATE_PATH: $CERTIFICATE_PATH"
          echo "PP_PATH: $PP_PATH"
          echo "KEYCHAIN_PATH: $KEYCHAIN_PATH"
          echo "P12_PASSWORD: $P12_PASSWORD"

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18.17.1'
      # - name: Clean workspace
      #   run: |
      #     git clean -ffdx
      #     npm cache clean --force

      # - name: Clean Xcode Build
      #   run: |
      #     cd ios
      #     xcodebuild clean -workspace ryman.xcworkspace -scheme ryman

      # - name: Install dependencies
      #   run: npm install --legacy-peer-deps

      # - name: Set up environment variables
      #   run:
      #     echo "${{ secrets.ENV_STAGE }}" > .env.stage1

      # - name: Run rnuc .env.stage1
      #   run: npx rnuc .env.stage1

      # - name: Install CocoaPods
      #   run: |
      #     sudo gem install cocoapods
      #     pod install --project-directory=ios
   
      # - name: build archive
      #   run: |
      #     cd ios
      #     xcodebuild -workspace ryman.xcworkspace \
      #     -scheme "ryman" \
      #     -sdk iphoneos \
      #     -configuration  \
      #     -destination generic/platform=iOS \
      #     -archivePath $RUNNER_TEMP/ryman.xcarchive \
      #     archive

      # - name: export ipa
      #   env:
      #     EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
      #   run: |
      #     EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
      #     echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
      #     xcodebuild -exportArchive -archivePath $RUNNER_TEMP/joplin.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build

      # - name: Upload application
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: RymanBuild
      #     path: ${{ runner.temp }}/build/Ryman.ipa
      #     retention-days: 3